# Generated by Django 4.2.2 on 2023-07-18 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appunidad7', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='datecompleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
