# Generated by Django 4.2.2 on 2023-06-28 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appunidad7', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo del Posteo')),
                ('content', models.TextField(verbose_name='Texto del Posteo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tzone', models.CharField(choices=[('EU', 'EUROPE'), ('US', 'UNITED STATES')], verbose_name='Zona Horaria')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
